language: cpp
sudo: required
dist: trusty
compiler:
- clang
- g++

branches:
  only:
  - master

install:
- sudo apt-get -y install libboost-all-dev libsnappy-dev realpath
- bash install_dependencies.sh
- bash compile_proto.sh
- bash run.sh build

script:
- cd cmake-build-debug && cmake .. && make -j4
- cd ../ && bash run.sh test